VPATH += keyboards/gboards

SRC += oneshot.c

VIA_ENABLE = yes
LTO_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = no
AUTO_SHIFT_ENABLE = no
COMBO_ENABLE = yes
SEND_STRING_ENABLE = yes
CAPS_WORD_ENABLE = yes
